-- ============================================================================
-- Sentinel AML — Core relational schema
-- Customer -> Account -> Transaction, plus Alert, Case, audit and reference data
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Customers (KYC master)
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_ref      VARCHAR(40)  NOT NULL UNIQUE,
    full_name         VARCHAR(200) NOT NULL,
    date_of_birth     DATE,
    national_id       VARCHAR(60),
    customer_type     VARCHAR(20)  NOT NULL,          -- RETAIL / BUSINESS
    risk_rating       VARCHAR(10)  NOT NULL DEFAULT 'LOW',  -- LOW / MEDIUM / HIGH
    residence_country VARCHAR(2)   NOT NULL,          -- ISO 3166-1 alpha-2
    email             VARCHAR(200),
    phone             VARCHAR(40),
    onboarded_at      TIMESTAMP,
    created_at        TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP    NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Accounts
-- ---------------------------------------------------------------------------
CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(40)  NOT NULL UNIQUE,
    customer_id    BIGINT       NOT NULL REFERENCES customers(id),
    account_type   VARCHAR(20)  NOT NULL,             -- CHECKING / SAVINGS / BUSINESS / WALLET
    currency       VARCHAR(3)   NOT NULL,
    opening_date   DATE         NOT NULL,
    risk_rating    VARCHAR(10)  NOT NULL DEFAULT 'LOW',
    status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX idx_accounts_customer ON accounts(customer_id);

-- ---------------------------------------------------------------------------
-- Transactions
-- ---------------------------------------------------------------------------
CREATE TABLE transactions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_ref              VARCHAR(60)   NOT NULL UNIQUE,
    account_id           BIGINT        NOT NULL REFERENCES accounts(id),
    direction            VARCHAR(10)   NOT NULL,       -- CREDIT / DEBIT
    txn_type             VARCHAR(20)   NOT NULL,       -- DEPOSIT / WITHDRAWAL / TRANSFER / PAYMENT
    amount               NUMERIC(19,2) NOT NULL,
    currency             VARCHAR(3)    NOT NULL,
    base_amount          NUMERIC(19,2) NOT NULL,       -- normalized to base currency (INR)
    counterparty_name    VARCHAR(200),
    counterparty_account VARCHAR(60),
    counterparty_country VARCHAR(2),
    channel              VARCHAR(20)   NOT NULL,       -- ONLINE / WIRE / ATM / BRANCH / MOBILE
    jurisdiction         VARCHAR(2),                   -- ISO country where txn occurred
    booked_at            TIMESTAMP     NOT NULL,       -- business timestamp of the transaction
    created_at           TIMESTAMP     NOT NULL DEFAULT now()
);
CREATE INDEX idx_txn_account            ON transactions(account_id);
CREATE INDEX idx_txn_booked_at          ON transactions(booked_at);
CREATE INDEX idx_txn_account_booked     ON transactions(account_id, booked_at);
CREATE INDEX idx_txn_cp_country         ON transactions(counterparty_country);

-- ---------------------------------------------------------------------------
-- Cases (analyst investigation container)
-- ---------------------------------------------------------------------------
CREATE TABLE cases (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_ref     VARCHAR(40)  NOT NULL UNIQUE,
    customer_id  BIGINT       NOT NULL REFERENCES customers(id),
    status       VARCHAR(20)  NOT NULL DEFAULT 'OPEN',   -- OPEN / INVESTIGATING / ESCALATED / CLOSED
    priority     VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM', -- LOW / MEDIUM / HIGH / CRITICAL
    title        VARCHAR(300) NOT NULL,
    summary      TEXT,
    assigned_to  VARCHAR(80),
    opened_by    VARCHAR(80)  NOT NULL,
    resolution   TEXT,
    opened_at    TIMESTAMP    NOT NULL DEFAULT now(),
    closed_at    TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX idx_cases_customer ON cases(customer_id);
CREATE INDEX idx_cases_status   ON cases(status);

-- ---------------------------------------------------------------------------
-- Alerts
-- ---------------------------------------------------------------------------
CREATE TABLE alerts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_ref          VARCHAR(40)  NOT NULL UNIQUE,
    customer_id        BIGINT       NOT NULL REFERENCES customers(id),
    account_id         BIGINT       REFERENCES accounts(id),
    rule_type          VARCHAR(40)  NOT NULL,          -- primary typology
    contributing_rules VARCHAR(300),                   -- comma-separated rule codes that reinforced this alert
    risk_score         INT          NOT NULL DEFAULT 0,-- 0..100
    severity           VARCHAR(10)  NOT NULL,          -- LOW / MEDIUM / HIGH / CRITICAL
    status             VARCHAR(20)  NOT NULL DEFAULT 'OPEN', -- OPEN / UNDER_REVIEW / ESCALATED / CLEARED / CONFIRMED
    title              VARCHAR(300) NOT NULL,
    explanation        TEXT         NOT NULL,
    dedup_key          VARCHAR(200) NOT NULL,          -- identity of the underlying pattern (for aggregation)
    disposition        VARCHAR(30),                    -- FALSE_POSITIVE / CONFIRMED_SUSPICIOUS / ESCALATED_SAR / ...
    disposition_reason TEXT,
    disposed_by        VARCHAR(80),
    disposed_at        TIMESTAMP,
    case_id            BIGINT       REFERENCES cases(id),
    created_at         TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_alert_dedup UNIQUE (dedup_key)
);
CREATE INDEX idx_alerts_customer   ON alerts(customer_id);
CREATE INDEX idx_alerts_status     ON alerts(status);
CREATE INDEX idx_alerts_risk_score ON alerts(risk_score DESC);
CREATE INDEX idx_alerts_case       ON alerts(case_id);

-- ---------------------------------------------------------------------------
-- Alert evidence (transactions supporting an alert)
-- ---------------------------------------------------------------------------
CREATE TABLE alert_evidence (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id       BIGINT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
    transaction_id BIGINT NOT NULL REFERENCES transactions(id),
    note           VARCHAR(300),
    CONSTRAINT uq_alert_evidence UNIQUE (alert_id, transaction_id)
);
CREATE INDEX idx_alert_evidence_alert ON alert_evidence(alert_id);

-- ---------------------------------------------------------------------------
-- Immutable audit trail (append-only; enforced at the application layer)
-- ---------------------------------------------------------------------------
CREATE TABLE audit_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type    VARCHAR(30)  NOT NULL,   -- ALERT / CASE
    entity_id      VARCHAR(40)  NOT NULL,
    action         VARCHAR(40)  NOT NULL,   -- CREATED / STATUS_CHANGED / DISPOSED / ASSIGNED / ...
    actor          VARCHAR(80)  NOT NULL,
    previous_state VARCHAR(40),
    new_state      VARCHAR(40),
    details        TEXT,
    occurred_at    TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_entity ON audit_events(entity_type, entity_id);

-- ---------------------------------------------------------------------------
-- Reference / configuration data
-- ---------------------------------------------------------------------------
CREATE TABLE rule_config (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code    VARCHAR(40)  NOT NULL UNIQUE,
    rule_type    VARCHAR(40)  NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    description  VARCHAR(500),
    enabled      BOOLEAN      NOT NULL DEFAULT true,
    base_weight  INT          NOT NULL DEFAULT 50,   -- contribution to risk score 0..100
    severity     VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    params_json  TEXT         NOT NULL DEFAULT '{}', -- rule-specific thresholds / windows
    updated_by   VARCHAR(80),
    updated_at   TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE exchange_rates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(3)     NOT NULL UNIQUE,
    rate_to_base  NUMERIC(19,6)  NOT NULL,           -- 1 unit currency = rate_to_base base-currency units
    updated_at    TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE TABLE high_risk_jurisdictions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code VARCHAR(2)   NOT NULL UNIQUE,
    country_name VARCHAR(120) NOT NULL,
    category     VARCHAR(20)  NOT NULL DEFAULT 'HIGH_RISK', -- SANCTIONED / HIGH_RISK
    active       BOOLEAN      NOT NULL DEFAULT true,
    notes        VARCHAR(300)
);

CREATE TABLE watchlist_counterparties (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL,
    country_code VARCHAR(2),
    category     VARCHAR(20)  NOT NULL DEFAULT 'SANCTIONED',
    active       BOOLEAN      NOT NULL DEFAULT true,
    notes        VARCHAR(300),
    CONSTRAINT uq_watchlist_name UNIQUE (name)
);
